# Generated by Django 3.2.19 on 2023-05-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='grade',
            field=models.DecimalField(decimal_places=1, default='0', max_digits=2, verbose_name='Оценка'),
        ),
    ]
