# Generated by Django 3.2.19 on 2023-05-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20230526_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingstar',
            name='value',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Значение'),
        ),
    ]
