version: '3.7'

services:
  web:
    container_name: flowers
    restart: always
    depends_on:
      db:
        condition: service_healthy
    build: ./flowers
    command: bash entrypoint.sh
    ports:
      - '8000:8000'
    env_file:
      - .env.dev

  db:
    image: postgres
    container_name: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d magazine"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    env_file:
      - .env.dev.db
